Server:
  port: 8082

Database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  user: "olegsemashko"
  password: 1703
  dbname: "avitoDB"


PageSize: 3

Admin:
  username: "Oleg"
  password: 0000